global:
  scrape_interval: 5s  # Intervalle pour collecter les métriques

scrape_configs:
  # Collecte des métriques de l'API FastAPI
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8000"]

  # Collecte des métriques système avec Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]



# scrape_interval : 
# Fréquence à laquelle Prometheus collectera les métriques (ici toutes les 5 secondes).
# job_name : 
# Nom attribué au job de collecte pour identifier facilement les métriques dans les tableaux de bord.
# targets : 
# Adresse de votre API (par défaut, localhost:8000 si Prometheus tourne sur la même machine que votre API).

# pour la containerisation va falloir mettre non localhost mais api car l'api tourne dans un 
# container different de prometheus, et la liaison est fait par un bridge(network)